### ISSUE TITLE
store files by md5 doesn't seem to be working

### ISSUE THREAD

**Issue by gwsales** [hosom/bro-file-extraction#11]
When adding store files by md5 to config.bro it doesn't seem to impact the file names of extracted files. Is there a way to change how the file is stored originally if md5 is present vs the fuid with `f$info$md5`?

`@load ./plugins/store-files-by-md5`

**Comment by hosom** [comment]
Please make sure you have configured `FileExtraction::path`. If the variable is left unset, this script will not run.
