### ISSUE TITLE
Installation Instruction wrong bro-pkg install bro/hosom/file-extraction

### ISSUE THREAD

**Issue by pcamposo0x4f** [hosom/bro-file-extraction#12]
for install this package you must remove bro/ 
bro-pkg install hosom/file-extraction (correct)
bro-pkg install bro/hosom/file-extraction (wrong)

also you can use zkg instead bro-pkg
dont forget install zkg with sudo pip install zkg

**Comment by hosom** [comment]
Thanks! The docs have been updated.
