### ISSUE TITLE
Can you convert to zeek

### ISSUE THREAD

**Issue by blacktop** [hosom/bro-file-extraction#14]
Can you please convert from bro to zeek?

**Comment by hosom** [comment]
Yep! I'll work on this today. 

Check out the zeek branch if you want to track the changes.

**Comment by hosom** [comment]
@blacktop Mind testing? I pushed a new version. This should now be compatible with zeek/zkg.

**Comment by blacktop** [comment]
Thank you!

When I ran I got the following: 

```bash
$ docker run --rm -v `pwd`/pcap:/pcap blacktop/zeek:3.1.1 -F -r smallFlows.pcap local file-extraction/plugins/extract-all-files.zeek "Site::local_nets += { 192.168.5.0/24, 10.0.2.0/24 }"

zeek version 3.1.1
warning in /usr/local/zeek/share/zeek/site/file-extraction/plugins/../././file-extensions.zeek, lines 90-91: multiple initializations for index (text/rtf)
```

**Comment by hosom** [comment]
I know what the issue is... I'll fix it in the morning. I caused an issue implementing someone else's request.

**Comment by hosom** [comment]
Should be fixed now.

**Comment by blacktop** [comment]
works great thank you! 👍
