### ISSUE TITLE
Storing extracted files by file hash name

### ISSUE THREAD

**Issue by dspruell-s01** [hosom/bro-file-extraction#15]
macOS 10.14
zeek version 3.1.2
zeek/hosom/file-extraction (installed: 2.0.3) (installed from zeek pkg manager)

Having what seems like an issue getting the plugins store-files-by-*.zeek to work. 

file-extraction is configured with `site/packages/file-extraction/config.zeek` containing:

```
module FileExtraction;
redef path = "";
@load ./plugins/extract-all-files.zeek
@load ./plugins/store-files-by-sha256.zeek
```

`site/local.zeek` is set to `@load packages` and `site/packages/packages.zeek` is set to `@load ./file-extraction`, and I can verify files are being extracted to disk.

With a run of Zeek against a PCAP, this is the result:

```
$ egrep 'file-extract' loaded_scripts.log 
    /usr/local/Cellar/zeek/3.1.2/share/zeek/site/packages/file-extraction/__load__.zeek
      /usr/local/Cellar/zeek/3.1.2/share/zeek/site/packages/file-extraction/main.zeek
        /usr/local/Cellar/zeek/3.1.2/share/zeek/site/packages/file-extraction/file-extensions.zeek
      /usr/local/Cellar/zeek/3.1.2/share/zeek/site/packages/file-extraction/config.zeek
        /usr/local/Cellar/zeek/3.1.2/share/zeek/site/packages/file-extraction/plugins/extract-all-files.zeek
        /usr/local/Cellar/zeek/3.1.2/share/zeek/site/packages/file-extraction/plugins/store-files-by-sha256.zeek

$ zeek-cut < files.log 
1588643444.082378	FbeEe53ts6OauGQ9B5	74.115.244.70	10.1.1.5	Cb4HP34zEptG6mo0Pc	HTTP	0	PE,MD5,EXTRACT,SHA1,SHA256	application/x-dosexec	-	4.443742	-	F	5265416	5265416	0	0	F	-	e4001cd6654ad6b53afd5018c57b3254	3743a5890931ce37d6e58a3a14b95bc614e54e85	bea9538673ef534043219b831887f9e14e3560e21243c517d97a82b20f2a7a85	HTTP-FbeEe53ts6OauGQ9B5.exe	F	-

$ ls extract_files/
HTTP-FbeEe53ts6OauGQ9B5.exe
```

I'm not clear why the file name is the default rather than the hash of the file.

**Comment by hosom** [comment]
Thanks for the detailed report. 

You need to redef `path` to a valid value. 

The check below prevents the rename from occurring if `path` hasn't been defined:

https://github.com/hosom/file-extraction/blob/a8f214c9f4aad1282e9f525daf4cdcf2b8864a16/scripts/plugins/store-files-by-md5.zeek#L7-L8

**Comment by hosom** [comment]
Let me know if that doesn't fix your issue and I'll be happy to take another look!

**Comment by dspruell-s01** [comment]
Thanks @hosom, it looks like I missed that feedback from commentary on a previous issue.

I noticed that the requirement to redef `path` isn't mentioned in the package documentation:

https://packages.zeek.org/packages/view/10f902bf-f435-11e9-9321-0a645a3f3086

I'm wondering though if setting path is required, or if a default can be applied. Is something like either of these feasible?

1. No default required, because an existing default from Zeek's `FileExtract` module results in files being written to `./extract_files/` -- so inherit `FileExtract::prefix` or similar
2. Change the `FileExtraction` explicit module level default to `./extract_files/` to be operational out of the box

Although (2) is just doing what (1) would do, just not the right way.
