### ISSUE TITLE
File Extraction in cluster mode

### ISSUE THREAD

**Issue by farhan1303** [hosom/bro-file-extraction#16]
I have installed zeek with pf_ring, but file extraction not working. please help me. Following are the configuration:-

[logger]
type=logger
host=localhost

[manager]
type=manager
host=localhost

[proxy-1]
type=proxy
host=localhost

[worker-1]
type=worker
host=localhost
interface=eno1
lb_method=pf_ring
lb_procs=5

**Comment by hosom** [comment]
Please confirm that you have: 

1. Installed this add-on and enabled it by loading it in your local configuration file.
2. Defined a path for file extraction to send files to by redefing `FileExtraction::path`

**Comment by farhan1303** [comment]
Thanks for considering
Extraction path is default (/opt/zeek/logs/current/extracted_files). In stand_alone mode it works fine but in cluster mode its not working (not extracting any file)
