### ISSUE TITLE
file-extraction is not extracting files everytime

### ISSUE THREAD

**Issue by vishal1kumar** [hosom/bro-file-extraction#5]
After installing the plugin, it is not extracting the file every time a file is monitored on the interface. Sometimes it dumps file with wrong size and sometimes not at all.

**Comment by hosom** [comment]
Thanks for using my plugin!

Could you please provide the following, so that I can better assist you?

1. The output of [Bro Doctor](https://github.com/ncsa/bro-doctor/), which can be installed through the package manager.
2. An example packet capture that I can use to recreate this issue. 
3. Your configuration for this plugin (found in config.bro).

**Comment by pravinyarolkar** [comment]
Hi @hosom ,

Sorry for the delayed update, Vishal is unavailable.

I am updating the thread with logs on his behalf.

**Bro Doctor Output**

root@pravin-virtual-machine:/opt/bro/share/bro/site# broctl doctor.bro
#################################################################
# Checking if many recent connections have a SAD or had history #
#################################################################
0.0%, 0 out of 177 connections are half duplex


################################################
# Checking for recent capture_loss.log entries #
################################################
Capture loss stats:
error: worker=bro loss_count=26 noloss_count=604 min_loss=0.0 max_loss=100.0 overall_loss=100.0


################################################################
# Checking what percentage of recent tcp connections show loss #
################################################################
0.0%, 0 out of 177 connections have capture loss


######################################################################
# Checking if any recent connections have been logged multiple times #
######################################################################
ok, only 0.0%, 0 out of 0 connections appear to be duplicate


###############################################################################
# Checking if bro is linked against a custom malloc like tcmalloc or jemalloc #
###############################################################################
error: configured to use a custom malloc=False


#####################################################################
# Checking if bro is linked against pf_ring if lb_method is pf_ring #
#####################################################################
configured to use pf_ring=False. linked against pf_ring=False


############################################
# Checking for recent reporter.log entries #
############################################
error: Found 16 reporter log files in the past 7 days
Recent reporter.log messages:
/opt/bro/share/bro/base/misc/find-checksum-offloading.bro, line 54 1505972987.797651 Reporter::WARNING Your interface is likely receiving invalid TCP and UDP checksums, most likely from NIC checksum offloading.  By default, packets with invalid checksums are discarded by Bro unless using the -C command-line option or toggling the 'ignore_checksums' variable.  Alternatively, disable checksum offloading by the network adapter to ensure Bro analyzes the actual checksums that are transmitted.
/opt/bro/share/bro/base/misc/find-checksum-offloading.bro, line 54 1505972566.852017 Reporter::WARNING Your interface is likely receiving invalid TCP and UDP checksums, most likely from NIC checksum offloading.  By default, packets with invalid checksums are discarded by Bro unless using the -C command-line option or toggling the 'ignore_checksums' variable.  Alternatively, disable checksum offloading by the network adapter to ensure Bro analyzes the actual checksums that are transmitted.
9 duplicate messages suppressed
/opt/bro/share/bro/base/misc/find-checksum-offloading.bro, line 54 1505972472.570879 Reporter::WARNING Your interface is likely receiving invalid UDP checksums, most likely from NIC checksum offloading.  By default, packets with invalid checksums are discarded by Bro unless using the -C command-line option or toggling the 'ignore_checksums' variable.  Alternatively, disable checksum offloading by the network adapter to ensure Bro analyzes the actual checksums that are transmitted.
1505972552.184898 Reporter::INFO received termination signal
1505972970.995570 Reporter::INFO received termination signal
11 duplicate messages suppressed
1505972552.184898 Reporter::INFO 77 packets received on interface ens160, 0 dropped
1505972970.995570 Reporter::INFO 2099 packets received on interface ens160, 0 dropped
1505970903.970897 Reporter::INFO 68 packets received on interface ens160, 0 dropped
1505972449.170660 Reporter::INFO 479 packets received on interface ens160, 0 dropped
1505970879.204911 Reporter::INFO 63239 packets received on interface ens160, 0 dropped
1505971051.178328 Reporter::INFO 3351 packets received on interface ens160, 0 dropped
1505972197.555651 Reporter::INFO 2211 packets received on interface ens160, 0 dropped
1505971439.633788 Reporter::INFO 1657 packets received on interface ens160, 0 dropped
1505918980.225314 Reporter::INFO 13753744 packets received on interface ens160, 0 dropped
1505919581.759780 Reporter::INFO 118 packets received on interface ens160, 0 dropped
/opt/bro/share/bro/base/misc/find-checksum-offloading.bro, line 54 1505919008.233719 Reporter::WARNING Your interface is likely receiving invalid TCP checksums, most likely from NIC checksum offloading.  By default, packets with invalid checksums are discarded by Bro unless using the -C command-line option or toggling the 'ignore_checksums' variable.  Alternatively, disable checksum offloading by the network adapter to ensure Bro analyzes the actual checksums that are transmitted.
1505919556.471180 Reporter::INFO 1166 packets received on interface ens160, 0 dropped
1505920257.494232 Reporter::INFO 1897 packets received on interface ens160, 0 dropped
1505920357.228179 Reporter::INFO 855 packets received on interface ens160, 0 dropped

**Attaching packet capture with .pcap file.**
[packet-captures.txt](https://github.com/hosom/file-extraction/files/1320153/packet-captures.txt)
**Not allowing to upload the .pcap file. Please do change the extension after downloading to .pcap.**

**This is the file which I was downloading.
Size : 77K**
[1a85bb10c8d294b3bbe9264e045dd2871363e6fc10dc04f403317061ba653099.pdf](https://github.com/hosom/file-extraction/files/1320156/1a85bb10c8d294b3bbe9264e045dd2871363e6fc10dc04f403317061ba653099.pdf)

**Below is the file downloaded by BRO.
Size : 4K**
[HTTP-FXJBAh1KutVHT2RVZk.pdf](https://github.com/hosom/file-extraction/files/1320152/HTTP-FXJBAh1KutVHT2RVZk.pdf)

**In another issue** when we are downloading files with file-extraction plugin is enabled, download stuck at 90-98% but resumes after sometime with wrong extracted file (size is very low compared to original)

**Comment by hosom** [comment]
Thank you for following up! I have identified your issue. You have not disabled checksum offloading on your NIC and have caused Bro to ignore packets. This means that you're 'missing' data. 

To test to be certain (I've already confirmed, but feel free to do so yourself), run Bro with the ```-C``` option, which disables checksum verification. 

For a permanent fix, you'll need to properly configure your interface for capture. The easiest way to do this is to use the [bro-interface-setup](https://github.com/ncsa/bro-interface-setup) plugin provided by NCSA. 

Please follow up and let me know that your issue is resolved.

**Comment by pravinyarolkar** [comment]
@hosom 

_Thanks for the help!_

I think we need some basic help here to configure bro.

We were using broctl command prompt for start stop the bro sensor and broctl don't have -C option to start with. So I have used -C option to start the bro.

I have used below command to run bro manually.

`bash /opt/bro/share/broctl/scripts/run-bro -1 -C -i ens160 -U .status -p broctl -p broctl-live -p standalone -p local -p bro local.bro broctl broctl/standalone broctl/auto`

Even after using this **-C** option to start the bro, its still showing same behavior of extracting half file as reported in above comments #3

If the downloading file is small  (I used file of 52kb size) then bro extracts the file of 51kb/52kb/50kb where most of the times cksum or md5sum is not matching with original file. Sometimes md5sum do matches.

If we are downloading file of size 200mb or more then it stop extracting the file after 100mb or 101mb that is failure.

**Is there any other configuration we need to do along with -C option?**

Please help us for the same. 

Thanks in advance.

**Comment by hosom** [comment]
The -C option isn't really something that you should be running with all of the time. You need to configure your capture interfaces correctly. This generally involves disabling checksum offloading and increasing your MTU size. It can require additional steps depending on your physical hardware. 

There's an excellent blog post that goes over some of this stuff [on the Security Onion website](http://blog.securityonion.net/2011/10/when-is-full-packet-capture-not-full.html).
