### ISSUE TITLE
Configuring file extraction to write files in a directory when reading pcap files

### ISSUE THREAD

**Issue by lagoon7** [hosom/bro-file-extraction#6]
Hello I am trying to also use this plugin however I can't get it to create a directory like ./extracted-files to put them in when I am reading a cap file. Do I also need the base policy extract-all-files? I do like the fact that I can add mime types arrays. Where can I specify the output path and directory? 

I am using bro 2.5.1 and the current github version of bro.

Thanks for working this.

**Comment by hosom** [comment]
Sorry for the slow response. 

You should be able to just load one of the plugin scripts ad-hoc to make this happen:

```
bro -r foo.pcap file-extraction/plugins/extract-all-files.bro
```

This will create a directory called ```extracted_files``` and extract all of the files to that directory.

**Comment by hosom** [comment]
Did the above help with your issue?

**Comment by blacktop** [comment]
@hosom is there something I can add to local.bro that will also enable "extract-all" ?

**Comment by hosom** [comment]
@load <path-to-plugin>/scripts/plugins/extract-all-files
