### ISSUE TITLE
Legacy office mime types missing

### ISSUE THREAD

**Issue by sevdog** [hosom/bro-file-extraction#8]
Actually in `extract-ms-office`  some legacy office mime types are missing:

From [fileext.com](http://filext.com/faq/office_mime_types.php):

ext | mime type
-- | --
.doc | application/msword
.dot | application/msword
.docx | application/vnd.openxmlformats-officedocument.wordprocessingml.document
.dotx | application/vnd.openxmlformats-officedocument.wordprocessingml.template
.docm | application/vnd.ms-word.document.macroEnabled.12
.dotm | application/vnd.ms-word.template.macroEnabled.12
.xls | application/vnd.ms-excel
.xlt | application/vnd.ms-excel
.xla | application/vnd.ms-excel
.xlsx | application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
.xltx | application/vnd.openxmlformats-officedocument.spreadsheetml.template
.xlsm | application/vnd.ms-excel.sheet.macroEnabled.12
.xltm | application/vnd.ms-excel.template.macroEnabled.12
.xlam | application/vnd.ms-excel.addin.macroEnabled.12
.xlsb | application/vnd.ms-excel.sheet.binary.macroEnabled.12
.ppt | application/vnd.ms-powerpoint
.pot | application/vnd.ms-powerpoint
.pps | application/vnd.ms-powerpoint
.ppa | application/vnd.ms-powerpoint
.pptx | application/vnd.openxmlformats-officedocument.presentationml.presentation
.potx | application/vnd.openxmlformats-officedocument.presentationml.template
.ppsx | application/vnd.openxmlformats-officedocument.presentationml.slideshow
.ppam | application/vnd.ms-powerpoint.addin.macroEnabled.12
.pptm | application/vnd.ms-powerpoint.presentation.macroEnabled.12
.potm | application/vnd.ms-powerpoint.template.macroEnabled.12
.ppsm | application/vnd.ms-powerpoint.slideshow.macroEnabled.12

See also [this gist](https://gist.github.com/acuppy/6047526)

**Comment by sevdog** [comment]
I forgot _RichTextFormat_:

ext | mime type
-- | --
.rtf | application/rtf
.rtf | application/x-rtf
.rtf | text/rtf
.rtf | text/richtext

**Comment by hosom** [comment]
@sevdog This is a good catch. Many of these mimetypes aren't actually defined within Bro itself, so it'll take me some time to add all of the ones in here that I missed but ARE supported. 

If you're interested in knowing what you're missing out on in the meantime... Bro's file signatures are all stored in [this directory](https://github.com/bro/bro/tree/master/scripts/base/frameworks/files/magic).

**Comment by hosom** [comment]
Wow that was a long time to get around to this. I grabbed all of the mimetypes that you listed and checked them against master. The only missing type was `text/rtf`.

The current master branch contains this mimetype.
