### ISSUE TITLE
How to filter files according to their contents

### ISSUE THREAD

**Issue by wangchencheng93** [hosom/bro-file-extraction#9]
Hello, I wonder if you could help me with this.
 I just want to filter files through regex, extract the files of contents  matching the regex.
I found a related filed named bof_buffer of fa_file type, but the size of it is small.  
I can't get the whole contents of the file before send it to file analyzers.
How can i do? Thank you very much.

**Comment by hosom** [comment]
It looks like you received an answer to your question in [Zeek Issue #302](https://github.com/zeek/zeek/issues/302), so I'm going to go ahead and close this.
